// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddCartItem implements addCartItem operation.
//
// Add an item to the cart.
//
// POST /cart/items
func (UnimplementedHandler) AddCartItem(ctx context.Context, req *AddCartItemRequest, params AddCartItemParams) (r AddCartItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ClearCart implements clearCart operation.
//
// Clear the current user's cart.
//
// DELETE /cart
func (UnimplementedHandler) ClearCart(ctx context.Context, params ClearCartParams) (r *Cart, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCart implements getCart operation.
//
// Get the current user's cart.
//
// GET /cart
func (UnimplementedHandler) GetCart(ctx context.Context, params GetCartParams) (r *Cart, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveCartItem implements removeCartItem operation.
//
// Remove an item from the cart.
//
// DELETE /cart/items/{product_id}
func (UnimplementedHandler) RemoveCartItem(ctx context.Context, params RemoveCartItemParams) (r *Cart, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCartItem implements updateCartItem operation.
//
// Update the quantity of an item in the cart.
//
// PUT /cart/items/{product_id}
func (UnimplementedHandler) UpdateCartItem(ctx context.Context, req *UpdateCartItemRequest, params UpdateCartItemParams) (r UpdateCartItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
