// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AddCartItemOperation    OperationName = "AddCartItem"
	ClearCartOperation      OperationName = "ClearCart"
	GetCartOperation        OperationName = "GetCart"
	RemoveCartItemOperation OperationName = "RemoveCartItem"
	UpdateCartItemOperation OperationName = "UpdateCartItem"
)
