// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/AddCartItemRequest
type AddCartItemRequest struct {
	ProductID string `json:"product_id"`
	Quantity  int    `json:"quantity"`
}

// GetProductID returns the value of ProductID.
func (s *AddCartItemRequest) GetProductID() string {
	return s.ProductID
}

// GetQuantity returns the value of Quantity.
func (s *AddCartItemRequest) GetQuantity() int {
	return s.Quantity
}

// SetProductID sets the value of ProductID.
func (s *AddCartItemRequest) SetProductID(val string) {
	s.ProductID = val
}

// SetQuantity sets the value of Quantity.
func (s *AddCartItemRequest) SetQuantity(val int) {
	s.Quantity = val
}

// Ref: #/components/schemas/Cart
type Cart struct {
	Items []CartItem `json:"items"`
	// Total price of all products in the cart.
	TotalPrice float64 `json:"total_price"`
}

// GetItems returns the value of Items.
func (s *Cart) GetItems() []CartItem {
	return s.Items
}

// GetTotalPrice returns the value of TotalPrice.
func (s *Cart) GetTotalPrice() float64 {
	return s.TotalPrice
}

// SetItems sets the value of Items.
func (s *Cart) SetItems(val []CartItem) {
	s.Items = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *Cart) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

func (*Cart) addCartItemRes()    {}
func (*Cart) updateCartItemRes() {}

// Ref: #/components/schemas/CartItem
type CartItem struct {
	// Unique identifier of the product.
	ProductID string `json:"product_id"`
	// Quantity of the product in the cart.
	Quantity int `json:"quantity"`
	// Detailed product data retrieved from the Product API.
	Product OptProduct `json:"product"`
	// Subtotal price for this item (quantity * price).
	Subtotal float64 `json:"subtotal"`
}

// GetProductID returns the value of ProductID.
func (s *CartItem) GetProductID() string {
	return s.ProductID
}

// GetQuantity returns the value of Quantity.
func (s *CartItem) GetQuantity() int {
	return s.Quantity
}

// GetProduct returns the value of Product.
func (s *CartItem) GetProduct() OptProduct {
	return s.Product
}

// GetSubtotal returns the value of Subtotal.
func (s *CartItem) GetSubtotal() float64 {
	return s.Subtotal
}

// SetProductID sets the value of ProductID.
func (s *CartItem) SetProductID(val string) {
	s.ProductID = val
}

// SetQuantity sets the value of Quantity.
func (s *CartItem) SetQuantity(val int) {
	s.Quantity = val
}

// SetProduct sets the value of Product.
func (s *CartItem) SetProduct(val OptProduct) {
	s.Product = val
}

// SetSubtotal sets the value of Subtotal.
func (s *CartItem) SetSubtotal(val float64) {
	s.Subtotal = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) addCartItemRes()    {}
func (*Error) updateCartItemRes() {}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptProduct returns new OptProduct with value set to v.
func NewOptProduct(v Product) OptProduct {
	return OptProduct{
		Value: v,
		Set:   true,
	}
}

// OptProduct is optional Product.
type OptProduct struct {
	Value Product
	Set   bool
}

// IsSet returns true if OptProduct was set.
func (o OptProduct) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptProduct) Reset() {
	var v Product
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptProduct) SetTo(v Product) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptProduct) Get() (v Product, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptProduct) Or(d Product) Product {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Product
type Product struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

// GetID returns the value of ID.
func (s *Product) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Product) GetName() string {
	return s.Name
}

// GetPrice returns the value of Price.
func (s *Product) GetPrice() float64 {
	return s.Price
}

// SetID sets the value of ID.
func (s *Product) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Product) SetName(val string) {
	s.Name = val
}

// SetPrice sets the value of Price.
func (s *Product) SetPrice(val float64) {
	s.Price = val
}

// Ref: #/components/schemas/UpdateCartItemRequest
type UpdateCartItemRequest struct {
	Quantity int `json:"quantity"`
}

// GetQuantity returns the value of Quantity.
func (s *UpdateCartItemRequest) GetQuantity() int {
	return s.Quantity
}

// SetQuantity sets the value of Quantity.
func (s *UpdateCartItemRequest) SetQuantity(val int) {
	s.Quantity = val
}
