// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddCartItem implements addCartItem operation.
	//
	// Add an item to the cart.
	//
	// POST /cart/items
	AddCartItem(ctx context.Context, req *AddCartItemRequest, params AddCartItemParams) (AddCartItemRes, error)
	// ClearCart implements clearCart operation.
	//
	// Clear the current user's cart.
	//
	// DELETE /cart
	ClearCart(ctx context.Context, params ClearCartParams) (*Cart, error)
	// GetCart implements getCart operation.
	//
	// Get the current user's cart.
	//
	// GET /cart
	GetCart(ctx context.Context, params GetCartParams) (*Cart, error)
	// RemoveCartItem implements removeCartItem operation.
	//
	// Remove an item from the cart.
	//
	// DELETE /cart/items/{product_id}
	RemoveCartItem(ctx context.Context, params RemoveCartItemParams) (*Cart, error)
	// UpdateCartItem implements updateCartItem operation.
	//
	// Update the quantity of an item in the cart.
	//
	// PUT /cart/items/{product_id}
	UpdateCartItem(ctx context.Context, req *UpdateCartItemRequest, params UpdateCartItemParams) (UpdateCartItemRes, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
