// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AddCartItemParams is parameters of addCartItem operation.
type AddCartItemParams struct {
	// The ID of the current user.
	XUserID string
}

func unpackAddCartItemParams(packed middleware.Parameters) (params AddCartItemParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-User-Id",
			In:   "header",
		}
		params.XUserID = packed[key].(string)
	}
	return params
}

func decodeAddCartItemParams(args [0]string, argsEscaped bool, r *http.Request) (params AddCartItemParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-User-Id.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-User-Id",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XUserID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-User-Id",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// ClearCartParams is parameters of clearCart operation.
type ClearCartParams struct {
	// The ID of the current user.
	XUserID string
}

func unpackClearCartParams(packed middleware.Parameters) (params ClearCartParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-User-Id",
			In:   "header",
		}
		params.XUserID = packed[key].(string)
	}
	return params
}

func decodeClearCartParams(args [0]string, argsEscaped bool, r *http.Request) (params ClearCartParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-User-Id.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-User-Id",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XUserID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-User-Id",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// GetCartParams is parameters of getCart operation.
type GetCartParams struct {
	// The ID of the current user.
	XUserID string
}

func unpackGetCartParams(packed middleware.Parameters) (params GetCartParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-User-Id",
			In:   "header",
		}
		params.XUserID = packed[key].(string)
	}
	return params
}

func decodeGetCartParams(args [0]string, argsEscaped bool, r *http.Request) (params GetCartParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-User-Id.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-User-Id",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XUserID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-User-Id",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// RemoveCartItemParams is parameters of removeCartItem operation.
type RemoveCartItemParams struct {
	// The ID of the current user.
	XUserID   string
	ProductID string
}

func unpackRemoveCartItemParams(packed middleware.Parameters) (params RemoveCartItemParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-User-Id",
			In:   "header",
		}
		params.XUserID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "product_id",
			In:   "path",
		}
		params.ProductID = packed[key].(string)
	}
	return params
}

func decodeRemoveCartItemParams(args [1]string, argsEscaped bool, r *http.Request) (params RemoveCartItemParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-User-Id.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-User-Id",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XUserID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-User-Id",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: product_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "product_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProductID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "product_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateCartItemParams is parameters of updateCartItem operation.
type UpdateCartItemParams struct {
	// The ID of the current user.
	XUserID   string
	ProductID string
}

func unpackUpdateCartItemParams(packed middleware.Parameters) (params UpdateCartItemParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-User-Id",
			In:   "header",
		}
		params.XUserID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "product_id",
			In:   "path",
		}
		params.ProductID = packed[key].(string)
	}
	return params
}

func decodeUpdateCartItemParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateCartItemParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-User-Id.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-User-Id",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XUserID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-User-Id",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: product_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "product_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProductID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "product_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
