// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetProductOperation   OperationName = "GetProduct"
	ListProductsOperation OperationName = "ListProducts"
)
